'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';

// Static export (output: 'export') does not honour `basePath` for server-side
// redirects generated by `redirect()`, so we redirect on the client with the
// Next router, which resolves `/bot` correctly under any base path
// (e.g. `/deriv-bot-next/bot` on GitHub Pages).
export default function RootPage() {
  const router = useRouter();

  useEffect(() => {
    router.replace('/bot');
  }, [router]);

  return null;
}
